export enum SystemRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN_FINANZAS = 'ADMIN_FINANZAS',
  ADMIN_RRHH = 'ADMIN_RRHH',
  ADMIN_NOMINA = 'ADMIN_NOMINA',
  CUENTA_MANAGER = 'CUENTA_MANAGER',
  VIEWER = 'VIEWER',
}
